### ISSUE TITLE
New version of Homebridge break the Selve plugin

### ISSUE THREAD

**Issue by cojoj** [tfohlmeister/homebridge-selve#18]
Hey, today in the morning I’ve noticed I can’t see any roller-shutters in my Home app. I went to theH to spot an error. Here’s the screenshot from the Homebridge’s console:
![22C3F367-7B63-4399-9578-287C0E0538AF](https://user-images.githubusercontent.com/4522407/201280370-b679fa09-e7d1-40ca-98be-35d5f7195a4b.png)
Following the hints in the error message I went to the Homebridge’s terminal and executed the following commend to downgrade Node.js version to the one _supported_:
```
hb-service update-node 16.18.1
```
As you may expected it worked fine, and brought back my accessories (although they’re no more assigned to the rooms etc.). I believe this plugin should bump the Node.js version, as it’s possible the temporary fix I did will last only till the next update 😉

**Comment by tfohlmeister** [comment]
Hey, thanks for the report - i noticed the same thing this morning :(

I solved it by re-installing the plugin but also lost my devices and had to reassign them.

I will work on a proper fix today or over the weekend!

**Comment by tfohlmeister** [comment]
Hey @cojoj,

i looked into this issue and I am not sure this is really something I can fix. As stated in the log message, the error occured because you are now using a different node version than previously.
The fix is also shown: Running `npm rebuild`. Since I already uninstalled and reinstalled the plugin on my system, would you please try and
* switch back to node 18
* run npm rebuild in your terminal?

I think the reason my plugin is prone to this kind of issue is that it is using external libraries (for serial port communication) that need to be compiled to fit the actual system + node version.

**Comment by cojoj** [comment]
I can confirm that running `npm rebuild` solves the problem when using Node.js 18.x 😉

**Comment by tfohlmeister** [comment]
Thanks for your help, closing this then! :)
